// @flow
export { default as common } from './common'
export { default as red } from './red'
export { default as pink } from './pink'
export { default as purple } from './purple'
export { default as blue } from './blue'
export { default as cyan } from './cyan'
export { default as green } from './green'
export { default as yellow } from './yellow'
export { default as orange } from './orange'
export { default as grey } from './grey'
